### ISSUE TITLE
dfc showing warnings about permissions

### ISSUE THREAD

**Issue by nrobinaubertin** [Rolinh/dfc#10]
Hello,
dfc is actually displaying warnings when it cannot stat some files/folders due to permissions.
I don't know if it's intended since df (from gnu coreutils) does not do that.

Again, I didn't read any code of dfc and I don't know if it's wanted.
Thanks for making this awesome tool !

**Comment by Rolinh** [comment]
Hi @nrobinaubertin,

Thanks for reporting this issue. Commit f584ba2084e5f3ba3f12e492eb7287c66f2ae729 fixes this behavior. I'll work on publishing a new version of dfc as soon as I find time to work on it. The new version is almost ready to be published.

Cheers!
