### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by benwaffle** [Rolinh/dfc#11]
I'd like to include it in the Solus repos: https://dev.solus-project.com/T2459

**Comment by Rolinh** [comment]
Absolutely, this is long due. I'm moving to a new place these days so kinda busy but I'll do it soon.

**Comment by Rolinh** [comment]
I've just release v3.1.0. You can download it from [here](https://projects.gw-computing.net/attachments/download/614/dfc-3.1.0.tar.gz).
